### ISSUE TITLE
When I try and run that, I get this issue...I also tried this with a pi user as well

### ISSUE THREAD

**Issue by reidcooper** [johnhamelink/bluetoothradio#4]
root@MusicBox:~/bluetoothradio# update-rc.d bluetooth-server defaults -force
update-rc.d: using dependency based boot sequencing
insserv: warning: script 'bluetooth-server' missing LSB tags and overrides
insserv: There is a loop between service monit and bluetooth-server if stopped
insserv:  loop involving service bluetooth-server at depth 2
insserv:  loop involving service monit at depth 1
insserv: Stopping bluetooth-server depends on monit and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header

**Comment by johnhamelink** [comment]
Hey @reidcooper sorry but this project isn't really maintained anymore. If you solve this issue feel free to submit a PR and I'll merge it in :smile: 

JH
